services:
  - type: web
    name: bosch-optimizer-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python predict_app.py"
    plan: free
    autoDeploy: true
